// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKG2PMXfkSJlUXeAUIno9hb2ZhG3UZV4',
    appId: '1:485571852874:web:d6a956668df91de02084b3',
    messagingSenderId: '485571852874',
    projectId: 'logistic-notifications-app',
    authDomain: 'logistic-notifications-app.firebaseapp.com',
    storageBucket: 'logistic-notifications-app.firebasestorage.app',
    measurementId: 'G-QK30NH8VVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZdJNaSPnySFRRdGZ90ZAizX_br7JtEvs',
    appId: '1:485571852874:android:fa4e7ee65d533fcb2084b3',
    messagingSenderId: '485571852874',
    projectId: 'logistic-notifications-app',
    storageBucket: 'logistic-notifications-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjYv5d0Pax1L57Dz7pPDnEq3kCnxH4QFc',
    appId: '1:485571852874:ios:798abb41e9e024492084b3',
    messagingSenderId: '485571852874',
    projectId: 'logistic-notifications-app',
    storageBucket: 'logistic-notifications-app.firebasestorage.app',
    iosBundleId: 'com.logistics.app.logisticsApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjYv5d0Pax1L57Dz7pPDnEq3kCnxH4QFc',
    appId: '1:485571852874:ios:798abb41e9e024492084b3',
    messagingSenderId: '485571852874',
    projectId: 'logistic-notifications-app',
    storageBucket: 'logistic-notifications-app.firebasestorage.app',
    iosBundleId: 'com.logistics.app.logisticsApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVKG2PMXfkSJlUXeAUIno9hb2ZhG3UZV4',
    appId: '1:485571852874:web:db9217adb7afb4ed2084b3',
    messagingSenderId: '485571852874',
    projectId: 'logistic-notifications-app',
    authDomain: 'logistic-notifications-app.firebaseapp.com',
    storageBucket: 'logistic-notifications-app.firebasestorage.app',
    measurementId: 'G-TQCHKYB9Q4',
  );
}
